### ISSUE TITLE
TypeError: 'type' object is not subscriptable

### ISSUE THREAD

**Issue by essg888** [mine-your-business/myb-lofty-python-api#8]
Ubuntu 20.04 LTS:

![image](https://user-images.githubusercontent.com/122754423/213054128-3a444d36-0bd7-4209-8e38-bd2cf1f0144a.png)

**Comment by piekstra** [comment]
@essg888 could you run `python3 --version` and show me the output?

**Comment by essg888** [comment]
> @essg888 could you run `python3 --version` and show me the output?

`root@localhost:~# python3 --version`
`Python 3.8.10`

**Comment by piekstra** [comment]
Doh. It looks like the type hints I provide require Python 3.9. I'll bump the specified requirements on the library so it gets flagged.

**Comment by essg888** [comment]
Issue resolved by upgrading Python to the minimum required version. Thank you!
